#!/bin/bash

# Make sure only root can run our script
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

cp wipe /usr/local/bin/
cp wipe@.service /etc/systemd/system/
systemctl daemon-reload

for n in $(echo {a..c}); do
	systemctl enable wipe@sd$n
done
