#!/bin/bash

# Run as root
if [ $EUID != 0 ]; then
    sudo "$0" "$@"
    exit $?
fi

UNIT="RPiDiskWiper"

for n in $(echo {a..z}); do
	systemctl disable $UNIT@sd$n
done

rm /etc/systemd/system/$UNIT@.service 
