#!/bin/bash

# Make sure only root can run our script
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

for n in $(echo {a..z}); do
	systemctl disable wipe@sd$n
done

rm /etc/systemd/system/wipe@.service 
